---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops
spec:
  replicas: 4
  selector:
    matchLabels:
      name: my-app
  template:
    metadata:
      labels:
        name: my-app
    spec:
      containers:
      - name: mycont
        image: shaikmustafa/cycle
        ports:
        - containerPort: 80
